builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
    main: .
    binary: hoge
archives:
  - id: gzip
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
